### ISSUE TITLE
Text onBlur

### ISSUE THREAD

**Issue by MichaelLeeHobbs** [nicolaslopezj/simple-react-form-material-ui#3]
Is this a bug or as intended? 

    onBlur (event) {
      this.props.onChange(this.state.value)
    }

Should it be?

    onBlur (event) {
      this.props.onBlur(this.state.value)
    }

**Comment by MichaelLeeHobbs** [comment]
I can make a pull request if you want, not sure if it was done this way intentionally and I am missing the reason why.

**Comment by nicolaslopezj** [comment]
It's saving the value when the input blurs, why is this giving you problems?

**Comment by MichaelLeeHobbs** [comment]
Password change form, needed to compare two fields onBlur

`    const onBlur = () => {
      if (this.state.newPassword !== this.state.repeatNewPassword) {
        this.setState({errorMessage: "Passwords must match!"})
      } else {
        this.setState({errorMessage: ""})
      }
    }`
...

`        <Field fieldName='repeatNewPassword' fieldType="password" label='Repeat New Password' onBlur={onBlur}
               errorMessage={this.state.errorMessage} type={TextWithBlur}
               onChange={(repeatNewPassword)=>this.setState({repeatNewPassword})}/>`
