### ISSUE TITLE
muiTheme error

### ISSUE THREAD

**Issue by wiredots01** [nicolaslopezj/simple-react-form-material-ui#4]
after following the example code...
got this error:
Failed context type: The context `muiTheme` is marked as required in `TextField`, but its value is `undefined`.
    in TextField (created by TextareaComponent)

**Comment by MichaelLeeHobbs** [comment]
@wiredots01 This is a requirement of Material UI now. Some where in your app you have to have a MuiThemeProvider. Most likely you want to do it at the top level. There are things you can do with the Theme Provider but I have not played with it yet other than to make it work.

Example:

    import React from "react";
    import MuiThemeProvider from "material-ui/styles/MuiThemeProvider";
    import {Container} from "muicss/react";
    /*...*/
    
    require('./app.scss');
    
    export class App extends React.Component {
      constructor(props) {
        super(props);
        this.state = {
          /*...*/
        }
        /*...*/
    
      }
    
      /*...*/
    
      // and example of how to pass props to children
      // {React.cloneElement(this.props.children, { playerControls: this.playerControls })}
    
      render() {
        return (
          <MuiThemeProvider>
            <div className="appBody">
              <AppNavigation />
              <Container fluid={true} className="childContainer">
                {this.props.children}
              </Container>
              /*...*/
            </div>
          </MuiThemeProvider>
        );
      }
    }
    
    App.propTypes = {
      children: React.PropTypes.element.isRequired,
    };

**Comment by wiredots01** [comment]
thanks its working now!
